### ISSUE TITLE
Cursor kicking makes `M-x delete-trailing-whitespace` delete newline at the end of each form feed

### ISSUE THREAD

**Issue by wasamasa** [wasamasa/form-feed#5]
`M-x delete-trailing-whitespace` contains a hack to counter Emacs assumption of a form feed being whitespace (yes, seriously).  The cursor kicking feature messes this hack up and makes the command delete a newline at the end of the displayed line which is not ok.

I can think of two ways of going at this. The fun way would involve writing a more powerful variant of `called-interactively-p` to detect whether the `point-entered` function was called by an interactive movement command.  The boring way would involve submitting a bug report for Emacs, providing a minimal example and explaining the actual problem in excruciating detail, hoping that someone will take a look at it and provide a fix.

**Comment by wasamasa** [comment]
Considering that Stefan is on a crusade to eradicate similiar behaviour and the fact that cursor kicking was added to avoid the visual glitch of point on such a line hiding it in graphical Emacs instances (textual ones don't expose this), I think I'll just remove the feature after handing in a bug report about that oddity.

**Comment by expez** [comment]
Bump

**Comment by wasamasa** [comment]
@expez You can temporarily work around this by customizing `form-feed-kick-cursor` *before* enabling `form-feed-mode`.  See https://github.com/wasamasa/form-feed/pull/2 for earlier discussion of this problem.

I'm writing a minimal example for reproducing the display bug and will submit a bug report afterwards, then I can dike the feature out and live with that glitch until its fixed in the Git release :)

**Comment by wasamasa** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21500

I don't ever expect it to get fixed, but I can deal with it.

**Comment by expez** [comment]
Great!

I did `(setq form-feed-kick-cursor nil)`, prior to starting the mode, and will keep watching this thread :)

**Comment by wasamasa** [comment]
Thanks for reminding me about this.

**Comment by wasamasa** [comment]
I've got a workaround for the cursor thing, see http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21500#35 for further details. This means that you'll need to customize the face in your theme, but eh, I can live with that.
