### ISSUE TITLE
form-feed-mode is erasing non-form-feed display properties

### ISSUE THREAD

**Issue by mmauger** [wasamasa/form-feed#7]
I am using form-feed and annotate which both use display properties to show things that are not really there. For some reason when I enable form-feed-mode the display items added by annotate-mode disappear despite the fact that there are no ^L's in the file (i.e., I wouldn't expect form-feed to have any effect).  I'm not sure where the problem exists, in form-feed or annotate but I've reorted it to both projects and have disabled form-feed in the interim.

**Comment by wasamasa** [comment]
I assume you're referring to [annotate.el](https://github.com/bastibe/annotate.el)?  I'm sort of shocked it's using overlays (so far, so good), but then manages display properties of the text on its own.  This can impossibly go well...

I'll install it and see what exactly happens when using both in parallel.

**Comment by wasamasa** [comment]
OK, I can reproduce it by loading up a minimal Emacs session, enabling `annotate-mode`, annotating something, then enabling `form-feed-mode`.  Interestingly enough, disabling `form-feed-mode` doesn't undo the change, not even disabling and enabling`annotate-mode` again makes new annotations appear.  Fixing the latter now...

**Comment by wasamasa** [comment]
This is as much as I can do from my side.  Basically, `form-feed-mode` is extending the font-lock machinery which deletes all instances of text properties it manages first, then performs the syntax highlighting pass.  So, to fix the other problem `annotate-mode` should be changed to use overlays exclusively.
