### ISSUE TITLE
Linum-mode

### ISSUE THREAD

**Issue by ksrb** [wasamasa/form-feed#8]
The overlay is going over the line numbers is there a way to stop this?

![overlay](https://cloud.githubusercontent.com/assets/3750409/14774913/f85ac86e-0a6f-11e6-8681-627e530a8b4e.png)

**Comment by wasamasa** [comment]
Ouch.  This is FWIW no overlay.  You get similiar overspilling effects with other packages and linum, like with paren highlighting.  I'm not sure whether that kind of thing is even fixable...

Did you consider trying out the [page-break-lines](https://github.com/purcell/page-break-lines) package instead?

**Comment by ksrb** [comment]
No worries, it's a nuance but a minor one for me.

I've looked at page-break-lines but I had some issues with it.

Thanks!
