### ISSUE TITLE
how to define ^L with comment

### ISSUE THREAD

**Issue by futurist** [wasamasa/form-feed#9]
In some white space clean mode, they don't allow special char and clean them up, include ^L char.

How to define ^L after a comment while as still keep the function of page break? That's to say `//^L` in Javascript as a whole to prevent clean up by some formatting lib.

**Comment by wasamasa** [comment]
Cleaning form feeds should not happen in the first place.  If you're using a tool that does this, it's a bug in that tool which needs to be fixed.

That being said, this used to happen on `M-x delete-trailing-whitespace` until I removed the cursor kicking code.  If that's your "white space clean mode", please update the package and try again.  If not, I'd still be curious what tool is doing that.

If you insist on defining form feeds as "Comments containing `^L`, feel free to modify `form-feed--font-lock-keywords` to contain an extra entry matching such comments.

**Comment by futurist** [comment]
It's [standard-format](https://github.com/maxogden/standard-format) for Javascript code, I'm sending the  whole buffer into that formatting and then get back. It will do some AST and ignore any independent `^L` char, but not `//^L`

**Comment by futurist** [comment]
I've found a way to `(setq page-delimiter "//^L")`, it's also passed into `form-feed--font-lock-keywords`, and it's solved the problem perfectly. Thank you!

**Comment by wasamasa** [comment]
Great!  Keep in mind though that `page-delimiter` is a global variable, so changing its value to that will keep the mode (and things like navigation by page) from working for other programming languages that don't have C++-style comments.  Try the following instead:

```elisp
(defun my-js-setup ()
  (set (make-local-variable 'page-delimiter) "//\f"))

(add-hook 'js-mode 'my-js-setup)
```

**Comment by futurist** [comment]
That's cool! better solution.
